[32m2022-04-20 21:06:01 -0400[0m - dagster - [34mDEBUG[0m - stage_game_data - 00efebc4-45fd-4d6d-86bf-0c21c5f32ab2 - 46571 - extract_game_ids_to_list - LOGS_CAPTURED - Started capturing logs for step: extract_game_ids_to_list.
[32m2022-04-20 21:06:01 -0400[0m - dagster - [34mDEBUG[0m - stage_game_data - 00efebc4-45fd-4d6d-86bf-0c21c5f32ab2 - 46571 - extract_game_ids_to_list - STEP_START - Started execution of step "extract_game_ids_to_list".
[32m2022-04-20 21:06:01 -0400[0m - dagster - [34mERROR[0m - [31mstage_game_data - 00efebc4-45fd-4d6d-86bf-0c21c5f32ab2 - 46571 - extract_game_ids_to_list - STEP_FAILURE - Execution of step "extract_game_ids_to_list" failed.

dagster.core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "extract_game_ids_to_list"::

AttributeError: 'str' object has no attribute 'strftime'

Stack Trace:
  File "/Users/alecryan/Desktop/nhl-analytics-pipleine-dagster/venv/lib/python3.7/site-packages/dagster/core/execution/plan/utils.py", line 47, in solid_execution_error_boundary
    yield
  File "/Users/alecryan/Desktop/nhl-analytics-pipleine-dagster/venv/lib/python3.7/site-packages/dagster/utils/__init__.py", line 401, in iterate_with_context
    next_output = next(iterator)
  File "/Users/alecryan/Desktop/nhl-analytics-pipleine-dagster/venv/lib/python3.7/site-packages/dagster/core/execution/plan/compute_generator.py", line 65, in _coerce_solid_compute_fn_to_iterator
    result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
  File "/Users/alecryan/Desktop/nhl-analytics-pipleine-dagster/nhl_elt/assets/nhl_to_s3.py", line 16, in extract_game_ids_to_list
    partition_key = context.output_asset_partition_key().strftime('%Y-%m-%d')
[0m
